### PR TITLE
Add support for handling mms, and add an --undo flag, so the changes aren't one-way

### PR DESCRIPTION
**Pull request by alexlance**

### CODE REVIEW

**Comment by alexlance** [comment]
Hi there @wearepariah here's the PR from the changes you suggested - thank you so much for pointing out the exact settings for mms.

**Comment by wearepariah** [comment]
amazing, thanks @alexlance 
flipping through reddit, it seems people have found the signal sms exporter doesn't export mms to import into another app
i reckon we can build something like that to export into an XML that can be imported using the SyncTech app

**Comment by alexlance** [comment]
oh wow - you're never gonna guess what I spent the last hour or so working on 😁 

Screen Shot 2022-10-16 at 5 24 54 pm

**Comment by alexlance** [comment]
@wearepariah  just running an SMS B&R import now - fingers crossed - here's the current code if you want to add any advice or suggestions:

https://github.com/alexlance/signal-message-exporter

**Comment by alexlance** [comment]
Ok made some tweaks to the message types and it's looking much better. But one thing, the import doesn't seem to have imported everything. The SMS B&R app said that everything had imported, but scrolling through the messages, and they're clearly not all there... if you get some time could please you try it out?

**Comment by alexlance** [comment]
Ah false alarm - everything imported ok! I think my old sms messaging app was a bit crufty. I installed a different messaging app and everything showed up. Looks like the https://github.com/alexlance/signal-message-exporter is good to go! (unless you find a bug :)

**Comment by wearepariah** [comment]
This all looks really good!
i have just started doing some tweaks to make the exporter cross-os compatible, and allow user-input if any of the relevant os variables aren't set. will send through a PR if it ends up being something i am comfortable with :)
great work @alexlance , thank you
EDIT: Clarified i was talking about the other repo

**Pull request merged**
